# Data manipulation

In [1]:
import pandas as pd
all_file = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/all_file/all_file.parquet", "fastparquet")
all_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94288 entries, 0 to 94287
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   source_code   94288 non-null  object
 1   source_idx    94288 non-null  int64
 2   compile_info  94288 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.2+ MB

In [2]:
all_file["compile_info"].describe()

count                       94288
unique                          1
top       <COMPILED_SUCCESSFULLY>
freq                        94288
Name: compile_info, dtype: object

In [3]:
contracts = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/contracts/contracts_filtered.parquet", engine="fastparquet")
contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   count            118663 non-null  int64
dtypes: int64(1), object(3)
memory usage: 3.6+ MB

In [4]:
contracts_v2 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/contracts/contracts_v2.parquet",  engine="fastparquet")
contracts_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   contract_ast     118663 non-null  object
 4   count            118663 non-null  object
dtypes: object(5)
memory usage: 4.5+ MB

In [5]:
contracts_v2[contracts_v2["contract_ast"] == "<PARSER_ERROR>"]

Empty DataFrame
Columns: [source_idx, contract_name, contract_source, contract_ast, count]
Index: []

In [7]:
import string
def normalized(s: str) -> str:
    s = s.replace(string.whitespace, " ")
    s = " ".join(s.split())
    return s

In [8]:
all_file_v2 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/solfile/all_file_v2.parquet", "fastparquet")
all_file_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94288 entries, 0 to 94287
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   source_code  94288 non-null  object
 1   ast          94288 non-null  object
dtypes: object(2)
memory usage: 1.4+ MB

In [9]:
base = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/base/deepseek_compile_error.parquet", engine="fastparquet")

In [5]:
base.head()

,contract_name,func_name,masked_contract,func_body,func_body_removed_comment,deepseek_output,file_source_idx,source_code,source_idx,compile_info
0,BitcoinAlliance,transferFrom,contract BitcoinAlliance is ERC20Detailed {\n\...,\r\n require(value <= _balances[from]);\r\n...,\n require(value <= _balances[from]);\n ...,\n require(value <= _balances[from]);\n ...,9311,/**\n * Bitcoin Alliance\n * There will be 3 l...,0,contracts/sample.sol:159:1: ParserError: Expec...
1,BasicToken,transfer,contract BasicToken is ERC20Basic {using SafeM...,require(_to != address(0));require(_value <= b...,require(_to != address(0));require(_value <= b...,require(_to != address(0));require(_value <= b...,56112,pragma solidity ^0.4.23;contract Ownable {addr...,1,<COMPILED_SUCCESSFULLY>
2,TokenBEP20,None,"contract TokenBEP20 is BEP20Interface, Owned{\...","\r\n symbol = ""NYINU"";\r\n name = ""NYAN ...","\n symbol = ""NYINU"";\n name = ""NYAN INU""...","\n symbol = ""TKN"";\n name = ""Token"";\n ...",53891,/**\n\nNyan Inu ($NYINU) is a community-focuse...,2,contracts/sample.sol:94:1: ParserError: Expect...
3,BZxProxy,setOracleRegistry,"contract BZxProxy is BZxStorage, Proxiable {\n...",\r\n if (_registry != address(0))\r\n ...,\n if (_registry != address(0))\n ...,\n if (_registry != address(0))\n ...,21459,"/*\n\n Copyright 2018 bZeroX, LLC\n\n Licens...",3,<COMPILED_SUCCESSFULLY>
4,KingdomStorage,startWar,contract KingdomStorage is ERC20 {\n using ...,\r\n\t\tuint invaderWarriorsNumber = getWarrio...,\n\t\tuint invaderWarriorsNumber = getWarriors...,"\n\t\temit War(_attacked, _invader, 0, 0);\n\t",48631,/**\n * https://GreenRabbit.site\n *\n * Welco...,4,<COMPILED_SUCCESSFULLY>

In [10]:
len(base[base["compile_info"] == "<COMPILED_SUCCESSFULLY>"])

3283

## Check contract filter

In [11]:
contract = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/contracts/contracts_filtered.parquet", "fastparquet")
contract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   count            118663 non-null  int64
dtypes: int64(1), object(3)
memory usage: 3.6+ MB

In [12]:
contract.head()

,source_idx,contract_name,contract_source,count
0,3511,Ownable,contract\tOwnable\t\t{\t\t\t\t\t\t\r\n\taddres...,54
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,1
2,64689,ERC20Mintable,"contract ERC20Mintable is BaseToken, MinterRol...",4
3,4397,Context,contract Context {\n constructor () interna...,7
4,540,ERC20Interface,contract ERC20Interface {\r\n function tota...,3809

In [13]:
contract["source_idx"] = contract["source_idx"].astype('int64')
contract['source_idx'].max()

94287

## Check all file version 2

In [13]:
all_file_v2 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/solfile/all_file_v2.parquet", "fastparquet")
all_file_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94288 entries, 0 to 94287
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   source_code  94288 non-null  object
 1   ast          94288 non-null  object
dtypes: object(2)
memory usage: 1.4+ MB

In [14]:
finetune = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/finetune/deepseek_compile_error.parquet", "fastparquet")
finetune.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5137 entries, 0 to 5136
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   contract_name              5137 non-null   object
 1   func_name                  4083 non-null   object
 2   masked_contract            5137 non-null   object
 3   func_body                  5137 non-null   object
 4   func_body_removed_comment  5137 non-null   object
 5   deepseek_output            5137 non-null   object
 6   file_source_idx            5137 non-null   int64
 7   source_code                5137 non-null   object
 8   source_idx                 5137 non-null   int64
 9   compile_info               5137 non-null   object
dtypes: int64(2), object(8)
memory usage: 401.5+ KB

In [15]:
test = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/finetune/deepseek_compile_error_and_inherit_element.parquet", "fastparquet")
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5137 entries, 0 to 5136
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   contract_name              5137 non-null   object
 1   func_name                  4083 non-null   object
 2   masked_contract            5137 non-null   object
 3   func_body                  5137 non-null   object
 4   func_body_removed_comment  5137 non-null   object
 5   deepseek_output            5137 non-null   object
 6   file_source_idx            5137 non-null   int64
 7   source_code                5137 non-null   object
 8   compile_info               5137 non-null   object
 9   inherit_elements           5137 non-null   object
dtypes: int64(1), object(9)
memory usage: 401.5+ KB

In [16]:
test["source_code"]

0       /**\n * Bitcoin Alliance\n * There will be 3 l...
1       pragma solidity ^0.4.23;contract Ownable {addr...
2       /**\n\nNyan Inu ($NYINU) is a community-focuse...
3       /*\n\n  Copyright 2018 bZeroX, LLC\n\n  Licens...
4       /**\n * https://GreenRabbit.site\n *\n * Welco...
                              ...
5132    pragma solidity ^0.4.24;\n\n// ---------------...
5133    /**\n *Submitted for verification at Etherscan...
5134    pragma solidity ^0.4.11;\n\n/**\n * SafeMath L...
5135    pragma solidity ^0.4.25;\n\ncontract DSNote {\...
5136    // SPDX-License-Identifier: MIT\n/**\n/*\n   _...
Name: source_code, Length: 5137, dtype: object

In [17]:
valid = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/compile_error_and_inherit_element/valid.parquet", "fastparquet")
valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27738 entries, 0 to 27737
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   contract_name              27738 non-null  object
 1   func_name                  21901 non-null  object
 2   masked_contract            27738 non-null  object
 3   func_body                  27738 non-null  object
 4   func_body_removed_comment  27738 non-null  object
 5   deepseek_output            27738 non-null  object
 6   file_source_idx            27738 non-null  int64
 7   source_code                27738 non-null  object
 8   compile_info               27738 non-null  object
 9   inherit_elements           27738 non-null  object
dtypes: int64(1), object(9)
memory usage: 2.1+ MB

In [20]:
valid.head()

,contract_name,func_name,masked_contract,func_body,func_body_removed_comment,deepseek_output,file_source_idx,source_code,compile_info,inherit_elements
0,HegicERCPool,send,"contract HegicERCPool is IERCLiquidityPool, Ow...","\r\n require(lockedAmount >= amount, ...","\n require(lockedAmount >= amount, ""P...",\n require(amount <= availableBalance...,83271,pragma solidity ^0.6.6;\n\nlibrary Address {\n...,<COMPILED_SUCCESSFULLY>,"['constructor () internal {<BODY>}', 'function..."
1,ERC20,transferFrom,"contract ERC20 is ERC20Interface,SafeMath {\n\...",\r\n require(_to != address(0));\r\n ...,\n require(_to != address(0));\n req...,\n require(_to != address(0));\n req...,63834,pragma solidity ^0.4.25;\n\ncontract SafeMath ...,<COMPILED_SUCCESSFULLY>,"['string public name;', 'string public symbol;..."
2,UniswapInterfaceMulticall,multicall,contract UniswapInterfaceMulticall {\n stru...,\n blockNumber = block.number;\n ...,\n blockNumber = block.number;\n ...,\n blockNumber = block.number;\n ...,48203,// SPDX-License-Identifier: MIT\npragma solidi...,<COMPILED_SUCCESSFULLY>,[]
3,WrappedToken,burnFrom,"contract WrappedToken is SecureContract, ERC20...","\r\n require(hasRole(_BURNFROM, msg.sen...","\n require(hasRole(_BURNFROM, msg.sende...","\n require(hasRole(_BURNFROM, msg.sende...",80658,// SPDX-License-Identifier: MIT\n\npragma soli...,<COMPILED_SUCCESSFULLY>,"['bytes32 public constant _ADMIN = keccak256(""..."
4,HWCIntegration,createTokenByHWC,contract HWCIntegration is BaseGameLogic {\n\r...,\r\n //convert eth to hwc\r\n ui...,\n \n uint256 tokenPrice = baseP...,\n require(hwcAddress[_userTo].index1 !...,40259,pragma solidity ^0.4.23;\n\n/**\n * @title Saf...,contracts/sample.sol:1113:16: DeclarationError...,"['uint public prizeFund = 0;', 'uint public ba..."

In [21]:
valid.loc[0, "inherit_elements"]

"['constructor () internal {<BODY>}', 'function owner() public view returns (address) {<BODY>}', 'function renounceOwnership() public virtual onlyOwner {<BODY>}', 'function transferOwnership(address newOwner) public virtual onlyOwner {<BODY>}', 'constructor (string memory name, string memory symbol) public {<BODY>}', 'function name() public view returns (string memory) {<BODY>}', 'function symbol() public view returns (string memory) {<BODY>}', 'function decimals() public view returns (uint8) {<BODY>}', 'function totalSupply() public view override returns (uint256) {<BODY>}', 'function balanceOf(address account) public view override returns (uint256) {<BODY>}', 'function transfer(address recipient, uint256 amount) public virtual override returns (bool) {<BODY>}', 'function allowance(address owner, address spender) public view virtual override returns (uint256) {<BODY>}', 'function approve(address spender, uint256 amount) public virtual override returns (bool) {<BODY>}', 'function transferFrom(address sender, address recipient, uint256 amount) public virtual override returns (bool) {<BODY>}', 'function increaseAllowance(address spender, uint256 addedValue) public virtual returns (bool) {<BODY>}', 'function decreaseAllowance(address spender, uint256 subtractedValue) public virtual returns (bool) {<BODY>}', 'function _transfer(address sender, address recipient, uint256 amount) internal virtual {<BODY>}', 'function _mint(address account, uint256 amount) internal virtual {<BODY>}', 'function _burn(address account, uint256 amount) internal virtual {<BODY>}', 'function _approve(address owner, address spender, uint256 amount) internal virtual {<BODY>}', 'function _setupDecimals(uint8 decimals_) internal {<BODY>}', 'function _beforeTokenTransfer(address from, address to, uint256 amount) internal virtual {<BODY>}', 'constructor () internal {<BODY>}', 'function _msgSender() internal view virtual returns (address payable) {<BODY>}', 'function _msgData() internal view virtual returns (bytes memory) {<BODY>}', 'constructor () internal {<BODY>}', 'function _msgSender() internal view virtual returns (address payable) {<BODY>}', 'function _msgData() internal view virtual returns (bytes memory) {<BODY>}']"

In [24]:
test = pd.read_json("/home/hieuvd/lvdthieu/CodeGen/data/test/refine/test.jsonl", lines=True)
test.head()

,source_idx,contract_name,func_name,masked_contract,func_body,func_body_removed_comment,len_input,len_output,total,deepseek_output
0,100499,BitcoinAlliance,transferFrom,contract BitcoinAlliance is ERC20Detailed {\n\...,\r\n require(value <= _balances[from]);\r\n...,\n require(value <= _balances[from]);\n ...,1472,370,1842,\n require(value <= _balances[from]);\n ...
1,66215,BasicToken,transfer,contract BasicToken is ERC20Basic {using SafeM...,require(_to != address(0));require(_value <= b...,require(_to != address(0));require(_value <= b...,120,77,197,\nbalances[msg.sender] = balances[msg.sender]....
2,107259,TokenBEP20,None,"contract TokenBEP20 is BEP20Interface, Owned{\...","\r\n symbol = ""NYINU"";\r\n name = ""NYAN ...","\n symbol = ""NYINU"";\n name = ""NYAN INU""...",710,96,806,"\n symbol = ""TKN"";\n name = ""Token"";\n ..."
3,76252,BZxProxy,setOracleRegistry,"contract BZxProxy is BZxStorage, Proxiable {\n...",\r\n if (_registry != address(0))\r\n ...,\n if (_registry != address(0))\n ...,1046,28,1074,\n if (_registry != address(0))\n ...
4,27168,KingdomStorage,startWar,contract KingdomStorage is ERC20 {\n using ...,\r\n\t\tuint invaderWarriorsNumber = getWarrio...,\n\t\tuint invaderWarriorsNumber = getWarriors...,1278,564,1842,\n\t\tuint lostCoins = getTributeValue(_invade...

In [25]:
test.loc[2,"deepseek_output"]

'\n    symbol = "TKN";\n    name = "Token";\n    decimals = 18;\n    _totalSupply = 10000000000000000000000000000000000000000;\n    balances[owner] = _totalSupply;\n    emit Transfer(address(0), owner, _totalSupply);\n  \n'

In [26]:
refine = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/refine/deepseek_compile_error.parquet", "fastparquet")
refine.head()

,contract_name,func_name,masked_contract,func_body,func_body_removed_comment,deepseek_output,file_source_idx,source_code,source_idx,compile_info
0,BitcoinAlliance,transferFrom,contract BitcoinAlliance is ERC20Detailed {\n\...,\r\n require(value <= _balances[from]);\r\n...,\n require(value <= _balances[from]);\n ...,\n require(value <= _balances[from]);\n ...,9311,/**\n * Bitcoin Alliance\n * There will be 3 l...,0,contracts/sample.sol:159:1: ParserError: Expec...
1,BasicToken,transfer,contract BasicToken is ERC20Basic {using SafeM...,require(_to != address(0));require(_value <= b...,require(_to != address(0));require(_value <= b...,\nbalances[msg.sender] = balances[msg.sender]....,56112,pragma solidity ^0.4.23;contract Ownable {addr...,1,<COMPILED_SUCCESSFULLY>
2,TokenBEP20,None,"contract TokenBEP20 is BEP20Interface, Owned{\...","\r\n symbol = ""NYINU"";\r\n name = ""NYAN ...","\n symbol = ""NYINU"";\n name = ""NYAN INU""...","\n symbol = ""TKN"";\n name = ""Token"";\n ...",53891,/**\n\nNyan Inu ($NYINU) is a community-focuse...,2,<COMPILED_SUCCESSFULLY>
3,BZxProxy,setOracleRegistry,"contract BZxProxy is BZxStorage, Proxiable {\n...",\r\n if (_registry != address(0))\r\n ...,\n if (_registry != address(0))\n ...,\n if (_registry != address(0))\n ...,21459,"/*\n\n Copyright 2018 bZeroX, LLC\n\n Licens...",3,<COMPILED_SUCCESSFULLY>
4,KingdomStorage,startWar,contract KingdomStorage is ERC20 {\n using ...,\r\n\t\tuint invaderWarriorsNumber = getWarrio...,\n\t\tuint invaderWarriorsNumber = getWarriors...,\n\t\tuint lostCoins = getTributeValue(_invade...,48631,/**\n * https://GreenRabbit.site\n *\n * Welco...,4,<COMPILED_SUCCESSFULLY>

## Calculate error type rate in the result

In [55]:
import pandas as pd
error_type = ["ParserError","DeclarationError","TypeError"]

finetune = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/finetune/deepseek_compile_error.parquet", "fastparquet")
refine = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/refine/deepseek_compile_error.parquet", "fastparquet")
base = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/base/deepseek_compile_error.parquet", "fastparquet")

In [65]:
stats = {"ParserError": [], "DeclarationError": [], "TypeError": []}
for i in error_type:
    stats[i].append(len(base[base["compile_info"].str.contains(i)]))
# for i in error_type:
#     stats[i].append(len(finetune[finetune["compile_info"].str.contains(i)]))
for i in error_type:
    stats[i].append(len(refine[refine["compile_info"].str.contains(i)]))
stats

{'ParserError': [1262, 432],
 'DeclarationError': [316, 280],
 'TypeError': [266, 262]}

In [62]:
print(len(refine[(refine["compile_info"].str.contains("TypeError")) & (refine["compile_info"].str.contains("DeclarationError"))]))

1

In [57]:
len(base[~base["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")])

1854

In [58]:
(316 - 8)

0.16612729234088458

In [66]:
stats["DeclarationError"][0] -= 8
stats["TypeError"][0] -= 8
stats["DeclarationError"][1] -= 1
df = pd.DataFrame(stats, index=["Deepseek base", "ReSC"])
df

               ParserError  DeclarationError  TypeError
Deepseek base         1262               308        258
ReSC                   432               279        262

In [31]:
import pandas as pd 
deepseek = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/codellama/deepseek_compile_error.parquet", "fastparquet")
# codellama = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/base/deepseek_compile_error.parquet", "fastparquet")

In [32]:
ERROR = [
    "ParserError",
    "DocstringParsingError",
    "SyntaxError",
    "DeclarationError",
    "TypeError",
    "UnimplementedFeatureError",
    "InternalCompilerError",
    "Exception",
    "CompilerError",
]
for error in ERROR:
    deepseek[error] = deepseek["compile_info"].str.contains(error)
deepseek.head()
def count_error(row):
    cnt = 0
    for error in ERROR:
        cnt += row[error]
    return cnt
deepseek["cnt_err"] = deepseek.apply(count_error, axis=1)

In [33]:
len(deepseek[deepseek["TypeError"] & deepseek["DeclarationError"]])

41

In [34]:
len(deepseek[deepseek["ParserError"]]) / len(deepseek[~deepseek["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")])

0.5483045425463852

In [41]:
(len(deepseek[deepseek["TypeError"]]) - 20) / len(deepseek[~deepseek["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")])

0.19961612284069097

In [42]:
(len(deepseek[deepseek["DeclarationError"]]) - 21) / len(deepseek[~deepseek["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")])

0.24504158669225848

In [44]:
x = len(deepseek[deepseek["ParserError"]]) / len(deepseek[~deepseek["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")]) + \
(len(deepseek[deepseek["TypeError"]]) - 20) / len(deepseek[~deepseek["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")]) + \
(len(deepseek[deepseek["DeclarationError"]]) - 21) / len(deepseek[~deepseek["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")])
x

0.9929622520793346

In [45]:
100 - 54.83 - 19.96 - 24.50

0.7100000000000009

In [46]:
data = [[68.07, 13.92, 16.61, 1.40], 
        [54.83, 19.96, 24.50, 0.71]]
df = pd.DataFrame(data, columns=["ParserError", "TypeError", "DeclarationError", "Other"], index=["Deepseek", "CodeLlama"])

In [47]:
df

           ParserError  TypeError  DeclarationError  Other
Deepseek         68.07      13.92             16.61   1.40
CodeLlama        54.83      19.96             24.50   0.71

# Data peeking

In [2]:
import pandas as pd

df = pd.read_json("/home/hieuvd/lvdthieu/CodeGen/data/validation/valid.jsonl", lines=True)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27738 entries, 0 to 27737
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   source_idx                 27738 non-null  int64
 1   contract_name              27738 non-null  object
 2   func_name                  21901 non-null  object
 3   masked_contract            27738 non-null  object
 4   func_body                  27738 non-null  object
 5   func_body_removed_comment  27738 non-null  object
 6   len_input                  27738 non-null  int64
 7   len_output                 27738 non-null  int64
 8   total                      27738 non-null  int64
 9   deepseek_output            27738 non-null  object
dtypes: int64(4), object(6)
memory usage: 2.1+ MB
None

In [4]:
valid_test_suite = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/validation/test_suite.parquet", "fastparquet")
valid_test_suite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27738 entries, 0 to 27737
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   contract_name              27738 non-null  object
 1   func_name                  21901 non-null  object
 2   masked_contract            27738 non-null  object
 3   func_body                  27738 non-null  object
 4   func_body_removed_comment  27738 non-null  object
 5   len_input                  27738 non-null  int64
 6   len_output                 27738 non-null  int64
 7   total                      27738 non-null  int64
 8   deepseek_output            27738 non-null  object
 9   file_source_idx            27738 non-null  int64
 10  file_source                27738 non-null  object
 11  filled_source_body         27738 non-null  object
 12  filled_source_deepseek     27738 non-null  object
dtypes: int64(4), object(9)
memory usage: 2.8+ MB

In [6]:
compile_error = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data/compile_info/base/deepseek_compile_error.parquet", "fastparquet")
compile_error.info()
compile_error.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5137 entries, 0 to 5136
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   contract_name              5137 non-null   object
 1   func_name                  4083 non-null   object
 2   masked_contract            5137 non-null   object
 3   func_body                  5137 non-null   object
 4   func_body_removed_comment  5137 non-null   object
 5   deepseek_output            5137 non-null   object
 6   file_source_idx            5137 non-null   int64
 7   source_code                5137 non-null   object
 8   source_idx                 5137 non-null   int64
 9   compile_info               5137 non-null   object
dtypes: int64(2), object(8)
memory usage: 401.5+ KB

,contract_name,func_name,masked_contract,func_body,func_body_removed_comment,deepseek_output,file_source_idx,source_code,source_idx,compile_info
0,BitcoinAlliance,transferFrom,contract BitcoinAlliance is ERC20Detailed {\n\...,\r\n require(value <= _balances[from]);\r\n...,\n require(value <= _balances[from]);\n ...,\n require(value <= _balances[from]);\n ...,9311,/**\n * Bitcoin Alliance\n * There will be 3 l...,0,contracts/sample.sol:159:1: ParserError: Expec...
1,BasicToken,transfer,contract BasicToken is ERC20Basic {using SafeM...,require(_to != address(0));require(_value <= b...,require(_to != address(0));require(_value <= b...,require(_to != address(0));require(_value <= b...,56112,pragma solidity ^0.4.23;contract Ownable {addr...,1,<COMPILED_SUCCESSFULLY>
2,TokenBEP20,None,"contract TokenBEP20 is BEP20Interface, Owned{\...","\r\n symbol = ""NYINU"";\r\n name = ""NYAN ...","\n symbol = ""NYINU"";\n name = ""NYAN INU""...","\n symbol = ""TKN"";\n name = ""Token"";\n ...",53891,/**\n\nNyan Inu ($NYINU) is a community-focuse...,2,contracts/sample.sol:94:1: ParserError: Expect...
3,BZxProxy,setOracleRegistry,"contract BZxProxy is BZxStorage, Proxiable {\n...",\r\n if (_registry != address(0))\r\n ...,\n if (_registry != address(0))\n ...,\n if (_registry != address(0))\n ...,21459,"/*\n\n Copyright 2018 bZeroX, LLC\n\n Licens...",3,<COMPILED_SUCCESSFULLY>
4,KingdomStorage,startWar,contract KingdomStorage is ERC20 {\n using ...,\r\n\t\tuint invaderWarriorsNumber = getWarrio...,\n\t\tuint invaderWarriorsNumber = getWarriors...,"\n\t\temit War(_attacked, _invader, 0, 0);\n\t",48631,/**\n * https://GreenRabbit.site\n *\n * Welco...,4,<COMPILED_SUCCESSFULLY>

In [2]:
import pandas as pd
all_file = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data_process/data/solfile/all_file.parquet", "fastparquet")
all_file.head()

                                         source_code
0  pragma solidity ^0.4.20;\r\n\r\nlibrary SafeMa...
1  // SPDX-License-Identifier: UNLICENSED\r\n\r\n...
2  // SPDX-License-Identifier: GPL-3.0-or-later\n...
3  pragma solidity ^0.8.0;\r\n\r\ninterface IERC2...
4  pragma solidity ^0.4.24;\r\n// This contract h...

In [3]:
all_file_v2 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data_process/data/solfile/all_file_v2.parquet", "fastparquet")
all_file_v2.head()

,source_code,ast
0,pragma solidity ^0.4.20;\r\n\r\nlibrary SafeMa...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
1,// SPDX-License-Identifier: UNLICENSED\r\n\r\n...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
2,// SPDX-License-Identifier: GPL-3.0-or-later\n...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
3,pragma solidity ^0.8.0;\r\n\r\ninterface IERC2...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
4,pragma solidity ^0.4.24;\r\n// This contract h...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."

In [10]:
import pandas as pd

base_385 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/base_385/result.parquet", "fastparquet")
error = base_385[~base_385["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")][["masked_contract", "func_body", "deepseek_output"]]
error.to_csv("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/base_385/base.csv")
with open("check.sol", "w") as f:
    f.write(base_385.loc[97, "source_code"])
base_385.loc[97, "compile_info"]

'contracts/sample.sol:204:23: DeclarationError: Undeclared identifier.\n    balances[_from] = sub(balances[_from], _value);\n                      ^-^\ncontracts/sample.sol:205:21: DeclarationError: Undeclared identifier. Did you mean "abi"?\n    balances[_to] = add(balances[_to], _value);\n                    ^-^\ncontracts/sample.sol:206:34: DeclarationError: Undeclared identifier.\n    allowed[_from][msg.sender] = sub(_allowance, _value);\n                                 ^-^'

In [3]:
import pandas as pd
chatGPT_385 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/final/result.parquet", "fastparquet")
error = chatGPT_385[~chatGPT_385["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")][["masked_contract", "func_body", "deepseek_output"]]
error.to_csv("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/.csv")
with open("check.sol", "w") as f:
    f.write(chatGPT_385.loc[97, "source_code"])
chatGPT_385.loc[97, "compile_info"]

'<COMPILED_SUCCESSFULLY>'

In [2]:
import pandas as pd
final_385 = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/final_385/result.parquet", "fastparquet")
error = final_385[~final_385["compile_info"].str.contains("<COMPILED_SUCCESSFULLY>")][["masked_contract", "func_body", "deepseek_output"]]
error.to_csv("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/final_385/final.csv")
with open("check.sol", "w") as f:
    f.write(final_385.loc[97, "source_code"])
final_385.loc[97, "compile_info"]

FileNotFoundError: [Errno 2] No such file or directory: '/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/final_385/result.parquet'

In [1]:
import pandas as pd
result = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/final/result.parquet", "fastparquet")
result = result[["contract_name", "func_name", "masked_contract", "func_body", "deepseek_output", "compile_info"]]
result.to_csv("/home/hieuvd/lvdthieu/CodeGen/data_process/data/compile_info/final/final.csv")

In [1]:
import pandas as pd

df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/solfile/all_file_v2.parquet", "fastparquet")
df

,source_code,ast
0,pragma solidity ^0.4.20;\r\n\r\nlibrary SafeMa...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
1,// SPDX-License-Identifier: UNLICENSED\r\n\r\n...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
2,// SPDX-License-Identifier: GPL-3.0-or-later\n...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
3,pragma solidity ^0.8.0;\r\n\r\ninterface IERC2...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
4,pragma solidity ^0.4.24;\r\n// This contract h...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
...,...,...
94283,//SPDX-License-Identifier: MIT\npragma solidit...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
94284,/*********************************************...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
94285,// SPDX-License-Identifier: GPL-3.0\r\n\r\npra...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
94286,// SPDX-License-Identifier: GPL-3.0\r\n\r\npra...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."
94287,// SPDX-License-Identifier: MIT\r\n\r\npragma ...,"{""type"":""SourceUnit"",""children"":[{""type"":""Prag..."

In [3]:
contract = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_filtered.parquet", "fastparquet")
contract

,source_idx,contract_name,contract_source,count
0,3511,Ownable,contract\tOwnable\t\t{\t\t\t\t\t\t\r\n\taddres...,54
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,1
2,64689,ERC20Mintable,"contract ERC20Mintable is BaseToken, MinterRol...",4
3,4397,Context,contract Context {\n constructor () interna...,7
4,540,ERC20Interface,contract ERC20Interface {\r\n function tota...,3809
...,...,...,...,...
118658,60352,Vault,contract Vault is Transferable {\r\n \r\n ...,1
118659,50945,MyAdvancedToken,"contract MyAdvancedToken is owned, TokenERC20 ...",1
118660,80297,PayerInterface,contract PayerInterface {\r\n\tfunction totalS...,1
118661,22220,EarthToken,contract EarthToken is ERC20 {\r\n construc...,1
118662,85966,POXToken,contract POXToken {\r\n /*=================...,1

# Check solidity data

In [2]:
import pandas as pd

df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_v2.parquet", "fastparquet")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   contract_ast     118663 non-null  object
 4   count            118663 non-null  object
dtypes: object(5)
memory usage: 4.5+ MB

In [3]:
with open("parse_sample.json", "w") as f:
    f.write(df.loc[0, "contract_ast"])

In [16]:
import pandas as pd
df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_masked.parquet", "fastparquet")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   source_idx        106402 non-null  object
 1   contract_name     106402 non-null  object
 2   func_name         95006 non-null   object
 3   masked_body       106402 non-null  object
 4   masked_all        106402 non-null  object
 5   func_body         106402 non-null  object
 6   signature_only    106402 non-null  object
 7   signature_extend  106402 non-null  object
dtypes: object(8)
memory usage: 7.2+ MB

In [21]:
df = df.dropna(how="all", axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 106402 entries, 0 to 118662
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   source_idx        106402 non-null  object
 1   contract_name     106402 non-null  object
 2   func_name         95006 non-null   object
 3   masked_body       106402 non-null  object
 4   masked_all        106402 non-null  object
 5   func_body         106402 non-null  object
 6   signature_only    106402 non-null  object
 7   signature_extend  106402 non-null  object
dtypes: object(8)
memory usage: 7.3+ MB

In [22]:
df.reset_index(drop=True, inplace=True)

In [23]:
df.to_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_masked_v1.parquet", "fastparquet")

In [24]:
df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_masked_v1.parquet", "fastparquet")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106402 entries, 0 to 106401
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   source_idx        106402 non-null  object
 1   contract_name     106402 non-null  object
 2   func_name         95006 non-null   object
 3   masked_body       106402 non-null  object
 4   masked_all        106402 non-null  object
 5   func_body         106402 non-null  object
 6   signature_only    106402 non-null  object
 7   signature_extend  106402 non-null  object
dtypes: object(8)
memory usage: 6.5+ MB

In [27]:
import pandas as pd

df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_v2.parquet", "fastparquet")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   contract_ast     118663 non-null  object
 4   count            118663 non-null  object
dtypes: object(5)
memory usage: 4.5+ MB

In [28]:
df.head()

,source_idx,contract_name,contract_source,contract_ast,count
0,0,Ownable,contract\tOwnable\t\t{\t\t\t\t\t\t\r\n\taddres...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",54
1,1,SCT,contract SCT is SafeMath{\r\n string public...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
2,2,ERC20Mintable,"contract ERC20Mintable is BaseToken, MinterRol...","{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",4
3,3,Context,contract Context {\n constructor () interna...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",7
4,4,ERC20Interface,contract ERC20Interface {\r\n function tota...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",3809

In [29]:
origin = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_filtered.parquet", "fastparquet")
origin.head()

,source_idx,contract_name,contract_source,count
0,3511,Ownable,contract\tOwnable\t\t{\t\t\t\t\t\t\r\n\taddres...,54
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,1
2,64689,ERC20Mintable,"contract ERC20Mintable is BaseToken, MinterRol...",4
3,4397,Context,contract Context {\n constructor () interna...,7
4,540,ERC20Interface,contract ERC20Interface {\r\n function tota...,3809

In [30]:
df["source_idx"] = origin["source_idx"]

,source_idx,contract_name,contract_source,contract_ast,count
0,3511,Ownable,contract\tOwnable\t\t{\t\t\t\t\t\t\r\n\taddres...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",54
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
2,64689,ERC20Mintable,"contract ERC20Mintable is BaseToken, MinterRol...","{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",4
3,4397,Context,contract Context {\n constructor () interna...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",7
4,540,ERC20Interface,contract ERC20Interface {\r\n function tota...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",3809

In [32]:
df.to_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_filtered_v1.parquet")

In [33]:
df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/data/masked_all_func_body_v1.parquet", "fastparquet")

In [38]:
df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/data/masked_all_func_body_v1.parquet", "fastparquet")

In [42]:
idxes = df["source_idx"].astype(int).to_list()
idxes = [int(x) for x in idxes]
idxes

[98056,
 4152,
 5258,
 86192,
 105452,
 44079,
 82440,
 31623,
 80907,
 20406,
 49298,
 80413,
 6536,
 100499,
 69340,
 65702,
 59011,
 53830,
 42378,
 57188,
 118288,
 96173,
 71661,
 182,
 8531,
 30596,
 108810,
 22486,
 19686,
 69384,
 73103,
 65681,
 16529,
 15745,
 68733,
 41183,
 35858,
 71423,
 24431,
 64351,
 102379,
 40421,
 118492,
 74497,
 53073,
 47508,
 3271,
 81785,
 96436,
 90543,
 1058,
 80941,
 43037,
 61870,
 69824,
 114174,
 27630,
 89319,
 30640,
 30733,
 60829,
 10191,
 104147,
 57516,
 86602,
 67741,
 103858,
 51143,
 98831,
 113350,
 90663,
 43299,
 37057,
 30719,
 17624,
 59300,
 117824,
 74539,
 34575,
 6874,
 16133,
 50574,
 53574,
 72915,
 47064,
 17287,
 60189,
 66075,
 45404,
 117452,
 18618,
 82017,
 75547,
 89180,
 76317,
 1744,
 94443,
 50332,
 118579,
 45654,
 66213,
 18349,
 63788,
 24505,
 102349,
 66215,
 24458,
 105340,
 114595,
 85740,
 97672,
 102013,
 78563,
 92146,
 32676,
 56522,
 17144,
 107259,
 15764,
 106014,
 111561,
 91072,
 110905,
 82421,
 72681,
 98800,
 65201,
 36050,
 66849,
 25008,
 60776,
 18755,
 35615,
 61518,
 42937,
 48666,
 41020,
 103697,
 88506,
 34711,
 68470,
 35799,
 33674,
 17625,
 50204,
 58610,
 40479,
 72862,
 62031,
 116915,
 70147,
 19876,
 56508,
 42333,
 21265,
 96367,
 10120,
 5464,
 66212,
 85429,
 61552,
 41077,
 118136,
 65084,
 14342,
 76252,
 83302,
 75143,
 97105,
 65275,
 52158,
 69805,
 83122,
 39312,
 6783,
 25410,
 27168,
 5930,
 1777,
 25766,
 10459,
 87481,
 66731,
 80148,
 82558,
 93618,
 87026,
 16951,
 16641,
 2701,
 47541,
 38508,
 20053,
 22157,
 59027,
 61322,
 76464,
 105242,
 5648,
 97521,
 103427,
 12373,
 13299,
 18702,
 110571,
 31576,
 58691,
 107582,
 31952,
 110750,
 70634,
 89885,
 50199,
 100212,
 104570,
 65514,
 115689,
 20304,
 50158,
 8934,
 23879,
 90178,
 43052,
 60988,
 101980,
 31331,
 104336,
 9778,
 103154,
 56406,
 32503,
 33139,
 6172,
 17783,
 50154,
 80243,
 115749,
 99324,
 52270,
 22798,
 69044,
 84272,
 114235,
 28413,
 56638,
 83112,
 39935,
 94304,
 13024,
 3046,
 98136,
 43012,
 54874,
 87565,
 43005,
 24266,
 79894,
 66953,
 54198,
 35286,
 18924,
 52906,
 53853,
 86607,
 58955,
 76340,
 110964,
 24922,
 114921,
 33377,
 104479,
 22377,
 83199,
 60555,
 11480,
 83236,
 23491,
 95840,
 2547,
 42061,
 67504,
 11660,
 106486,
 16655,
 89829,
 3852,
 115851,
 111099,
 103600,
 55381,
 93705,
 108072,
 58104,
 42618,
 10562,
 26175,
 101518,
 32772,
 22820,
 23275,
 45608,
 100960,
 72983,
 71842,
 114168,
 59972,
 100942,
 61643,
 93534,
 80655,
 57049,
 50171,
 20642,
 62478,
 109544,
 6236,
 89763,
 77570,
 73039,
 21541,
 6030,
 38147,
 89345,
 35688,
 30060,
 95887,
 107376,
 14037,
 94422,
 111834,
 25250,
 18055,
 93218,
 43648,
 17344,
 62831,
 70510,
 35664,
 59266,
 118399,
 46117,
 85129,
 27908,
 52374,
 47261,
 86438,
 61784,
 98557,
 74248,
 115275,
 91902,
 73592,
 115493,
 83921,
 23631,
 68631,
 43815,
 73359,
 103698,
 58007,
 106444,
 74814,
 70375,
 96253,
 109033,
 103675,
 106489,
 41358,
 114015,
 112432,
 406,
 49051,
 107240,
 82009,
 82246,
 24787,
 89926,
 11569,
 69124,
 38824,
 95870,
 77233,
 43526,
 33162,
 74594,
 43880,
 63815,
 76986,
 117299,
 83595,
 65969,
 59750,
 76651,
 101616,
 42958,
 52103,
 42921,
 114993,
 22427,
 112296,
 50760,
 51089,
 21365,
 75606,
 13145,
 107140,
 76823,
 71815,
 77292,
 20876,
 39071,
 26750,
 82695,
 96685,
 115814,
 112223,
 22946,
 72149,
 69659,
 46106,
 110528,
 95981,
 22902,
 95961,
 87152,
 44860,
 106983,
 41861,
 18252,
 66170,
 16473,
 15144,
 29263,
 81127,
 101270,
 118521,
 118197,
 92912,
 1017,
 96347,
 52816,
 60243,
 82145,
 52736,
 19192,
 66538,
 56181,
 55188,
 46711,
 69529,
 30398,
 110005,
 110754,
 52722,
 29666,
 44062,
 47522,
 110218,
 29945,
 90311,
 80241,
 24521,
 34233,
 108809,
 86865,
 59890,
 115515,
 108168,
 81089,
 110274,
 31829,
 106612,
 30363,
 105971,
 89159,
 12808,
 27122,
 65982,
 98064,
 22186,
 113606,
 33456,
 90247,
 115635,
 59374,
 101645,
 56495,
 81205,
 85436,
 80079,
 48619,
 91507,
 108646,
 81846,
 117623,
 14929,
 29350,
 99754,
 42768,
 101307,
 8312,
 9153,
 26763,
 8821,
 80210,
 58654,
 49367,
 95782,
 15825,
 33052,
 30214,
 37774,
 7752,
 92422,
 101617,
 32793,
 37638,
 10627,
 53,
 102562,
 34545,
 18218,
 114055,
 48785,
 77173,
 49604,
 30566,
 110769,
 58133,
 54915,
 19364,
 90618,
 68767,
 21167,
 103705,
 59843,
 9675,
 72692,
 110351,
 43413,
 13894,
 110455,
 89376,
 63439,
 87913,
 2619,
 74049,
 81044,
 6358,
 112605,
 15100,
 107778,
 103978,
 24254,
 23898,
 84465,
 62074,
 86042,
 103477,
 102203,
 116797,
 42787,
 39943,
 98550,
 51496,
 78974,
 117698,
 29789,
 49029,
 114087,
 22768,
 7359,
 112159,
 49336,
 111158,
 68070,
 8016,
 36876,
 65155,
 105297,
 36888,
 29522,
 118089,
 46020,
 66515,
 60886,
 28717,
 74700,
 106737,
 84674,
 31524,
 34778,
 32757,
 98115,
 100957,
 81053,
 22434,
 96603,
 31609,
 102476,
 2384,
 47875,
 103980,
 43345,
 112186,
 8595,
 109338,
 36791,
 57162,
 27965,
 62130,
 53856,
 105639,
 38952,
 40203,
 113135,
 26142,
 81443,
 22336,
 73436,
 71990,
 113012,
 90773,
 51935,
 90115,
 70390,
 90235,
 32202,
 2096,
 22896,
 84696,
 109612,
 22802,
 81328,
 102219,
 14277,
 41552,
 48756,
 23081,
 48341,
 49612,
 35657,
 80946,
 82891,
 73334,
 84253,
 48837,
 88675,
 100166,
 14085,
 90709,
 36748,
 88998,
 30208,
 44373,
 112215,
 90867,
 57991,
 108609,
 29867,
 92891,
 47467,
 61965,
 67367,
 44952,
 35400,
 26349,
 20321,
 103119,
 54159,
 106371,
 71561,
 57777,
 118428,
 99344,
 18868,
 24892,
 17018,
 82111,
 99249,
 50071,
 98655,
 33742,
 82198,
 62045,
 16670,
 1141,
 7755,
 107210,
 95071,
 53983,
 31185,
 100799,
 16532,
 2675,
 113559,
 54114,
 102463,
 9018,
 94356,
 34943,
 36054,
 37743,
 92221,
 117594,
 66636,
 36321,
 56879,
 91087,
 61860,
 83000,
 15307,
 41595,
 82820,
 52872,
 76229,
 23318,
 98561,
 34415,
 96651,
 61948,
 100671,
 108598,
 34739,
 55395,
 1336,
 2145,
 77844,
 62053,
 39883,
 6933,
 21217,
 3931,
 112497,
 45879,
 46870,
 43344,
 103851,
 78935,
 50509,
 60750,
 74965,
 58150,
 42574,
 11894,
 59406,
 3442,
 27480,
 52317,
 94817,
 103382,
 40733,
 117363,
 16433,
 52360,
 47125,
 48882,
 104873,
 105232,
 35516,
 56574,
 105656,
 55084,
 80220,
 62803,
 59209,
 74856,
 39207,
 94549,
 91849,
 10847,
 41242,
 82956,
 118444,
 53385,
 2874,
 109337,
 1257,
 56328,
 108389,
 113650,
 86520,
 82546,
 104712,
 10006,
 45153,
 91536,
 84839,
 96820,
 77755,
 33947,
 64720,
 18270,
 113273,
 101258,
 59307,
 70408,
 96007,
 10914,
 23558,
 88316,
 32578,
 38818,
 97385,
 100152,
 68494,
 66604,
 70200,
 82447,
 110436,
 70175,
 74130,
 20427,
 107822,
 75754,
 82772,
 66738,
 98933,
 111906,
 51487,
 97808,
 47867,
 98790,
 4092,
 78314,
 108883,
 95566,
 89522,
 8336,
 83127,
 91528,
 22230,
 27277,
 36483,
 50102,
 77847,
 81610,
 33860,
 24177,
 77193,
 111422,
 89013,
 56745,
 89216,
 11862,
 18578,
 90286,
 65129,
 44009,
 69993,
 44013,
 65222,
 98130,
 31209,
 89417,
 96119,
 62640,
 68960,
 40613,
 21496,
 92189,
 10277,
 107371,
 77467,
 48333,
 34385,
 76810,
 80017,
 60262,
 33565,
 26210,
 80283,
 30952,
 30669,
 80339,
 75482,
 84282,
 15356,
 75094,
 82591,
 104982,
 87662,
 51809,
 71700,
 107928,
 89251,
 95346,
 55955,
 108044,
 17920,
 44963,
 93552,
 110819,
 81717,
 107897,
 110916,
 61364,
 64912,
 114780,
 58970,
 77750,
 53475,
 86283,
 113888,
 84824,
 67523,
 7347,
 65359,
 111839,
 96462,
 3308,
 80236,
 117550,
 14435,
 47157,
 55127,
 62558,
 87109,
 55509,
 90438,
 50109,
 51373,
 84118,
 38052,
 114969,
 20093,
 49131,
 74904,
 114311,
 81832,
 18939,
 30129,
 117247,
 4607,
 56147,
 10576,
 103623,
 48096,
 78751,
 88926,
 87354,
 70034,
 4834,
 83545,
 1427,
 11304,
 87204,
 64452,
 13253,
 84461,
 111854,
 20719,
 16502,
 24238,
 60044,
 112061,
 31831,
 23761,
 44489,
 27479,
 15872,
 79603,
 39648,
 117764,
 38930,
 12596,
 25519,
 105510,
 112031,
 73372,
 107355,
 77759,
 8268,
 30657,
 35120,
 455,
 15266,
 96,
 61365,
 70609,
 41968,
 53185,
 18215,
 117914,
 29267,
 74640,
 116630,
 110954,
 89834,
 86126,
 57996,
 79232,
 57590,
 53252,
 11393,
 20475,
 111477,
 98485,
 54086,
 99465,
 ...]

In [45]:
contracts = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_filtered_v1.parquet", "fastparquet")

In [46]:
contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   contract_ast     118663 non-null  object
 4   count            118663 non-null  object
dtypes: object(5)
memory usage: 4.5+ MB

In [47]:
contracts = contracts[contracts.index.isin(idxes)]
contracts.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74288 entries, 1 to 118662
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   source_idx       74288 non-null  object
 1   contract_name    74288 non-null  object
 2   contract_source  74288 non-null  object
 3   contract_ast     74288 non-null  object
 4   count            74288 non-null  object
dtypes: object(5)
memory usage: 3.4+ MB

In [48]:
contracts.head()

,source_idx,contract_name,contract_source,contract_ast,count
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
7,2251,Multisig,contract Multisig {\r\n // Maintain a mapping...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
11,82527,Ownable,contract Ownable {\r\n address public owner...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",12
12,40928,daocrowdsale,contract daocrowdsale is Ownable {\r\n usin...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
16,11986,Discount,contract Discount {\n\n address public owne...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",14

In [49]:
contracts.to_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_v2.parquet", "fastparquet")

In [50]:
test = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_v2.parquet", "fastparquet")
test.head()

,source_idx,contract_name,contract_source,contract_ast,count
index,,,,,
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
7,2251,Multisig,contract Multisig {\r\n // Maintain a mapping...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
11,82527,Ownable,contract Ownable {\r\n address public owner...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",12
12,40928,daocrowdsale,contract daocrowdsale is Ownable {\r\n usin...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",1
16,11986,Discount,contract Discount {\n\n address public owne...,"{""type"":""SourceUnit"",""children"":[{""type"":""Cont...",14

In [51]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74288 entries, 1 to 118662
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   source_idx       74288 non-null  object
 1   contract_name    74288 non-null  object
 2   contract_source  74288 non-null  object
 3   contract_ast     74288 non-null  object
 4   count            74288 non-null  object
dtypes: object(5)
memory usage: 3.4+ MB

In [54]:
df = pd.read_parquet("/home/hieuvd/lvdthieu/CodeGen/solidity_data/data/contracts/contracts_filtered.parquet", "fastparquet")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118663 entries, 0 to 118662
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   source_idx       118663 non-null  object
 1   contract_name    118663 non-null  object
 2   contract_source  118663 non-null  object
 3   count            118663 non-null  int64
dtypes: int64(1), object(3)
memory usage: 3.6+ MB

In [55]:
df.head()

,source_idx,contract_name,contract_source,count
0,3511,Ownable,contract\tOwnable\t\t{\t\t\t\t\t\t\r\n\taddres...,54
1,71542,SCT,contract SCT is SafeMath{\r\n string public...,1
2,64689,ERC20Mintable,"contract ERC20Mintable is BaseToken, MinterRol...",4
3,4397,Context,contract Context {\n constructor () interna...,7
4,540,ERC20Interface,contract ERC20Interface {\r\n function tota...,3809